spin_manifest_version = 2

[application]
name = "sos-c1"
version = "0.1.0"
authors = ["franxois <franxoois+github@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "sos-c1"
[[trigger.http]]
route = "/crypto"
component = "encryption-module"

[component.sos-c1]
source = "target/wasm32-wasi/release/sos_c1.wasm"
allowed_outbound_hosts = ["http://localhost:3000","https://sos-c1-9aej0qyi.fermyon.app"]

[component.sos-c1.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.encryption-module]
source = "../encryption-module/main.wasm"
allowed_outbound_hosts = []
